/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.EstoqueController;
import Models.DAO.ProdutoDAO;
import Models.Produto;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marcu
 */
public class Estoque extends javax.swing.JFrame {

    /**
     * Creates new form Estoque
     */
    
    EstoqueController controller;
    
    public Estoque() {
        initComponents();
        this.controller = new EstoqueController(this);
        listarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTabbedPane1Guias = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField4QuantidadeProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3MarcaProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2CodigoProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1NomeProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox2Generico = new javax.swing.JCheckBox();
        jCheckBox1Medicamento = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jFormattedTextField1ValorProduto = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2NomProduto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2CodProduto = new javax.swing.JTextField();
        jButton3buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Produto = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox2Generico1 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jTextField1NomeProduto1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField2CodigoProduto1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextField1ValorProduto1 = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField3MarcaProduto1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField4QuantidadeProduto1 = new javax.swing.JTextField();
        jCheckBox1Medicamento1 = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1Guias.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField4QuantidadeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4QuantidadeProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4QuantidadeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 160, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Quantidade do produto:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel1.add(jTextField3MarcaProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Marca do produto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel1.add(jTextField2CodigoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nome do produto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel1.add(jTextField1NomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 300, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Código do produto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jCheckBox2Generico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox2Generico.setText("Genérico");
        jCheckBox2Generico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2GenericoActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2Generico, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 130, 30));

        jCheckBox1Medicamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1Medicamento.setText("Medicamento");
        jPanel1.add(jCheckBox1Medicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Valor do produto:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, 20));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Cadastrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 140, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Editar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 140, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Apagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 140, 50));

        jFormattedTextField1ValorProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField1ValorProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ValorProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField1ValorProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 130, 30));

        jTabbedPane1Guias.addTab("Cadastro de Produto", jPanel1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nome do produto:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Código do produto:");

        jButton3buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3buscar.setText("Buscar");
        jButton3buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3buscarActionPerformed(evt);
            }
        });

        jTable1Produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Marca", "Quantidade Total", "Quantidade Atual", "Quantidade Vendida", "Valor Total", "Desconto", "Valor Atual"
            }
        ));
        jTable1Produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1ProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1Produto);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField2NomProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2CodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2NomProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jButton3buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2CodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPane1Guias.addTab("Consulta de produtos", jPanel2);

        jCheckBox2Generico1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox2Generico1.setText("Genérico");
        jCheckBox2Generico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2Generico1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Nome do produto:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Código do produto:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Valor do produto:");

        jFormattedTextField1ValorProduto1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField1ValorProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ValorProduto1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Marca do produto:");

        jTextField3MarcaProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3MarcaProduto1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Quantidade do produto:");

        jTextField4QuantidadeProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4QuantidadeProduto1ActionPerformed(evt);
            }
        });

        jCheckBox1Medicamento1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1Medicamento1.setText("Medicamento");

        jButton5.setText("Editar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTextField1NomeProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3MarcaProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBox1Medicamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox2Generico1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jTextField2CodigoProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jFormattedTextField1ValorProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField4QuantidadeProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1NomeProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField2CodigoProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3MarcaProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextField1ValorProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1Medicamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox2Generico1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4QuantidadeProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1Guias.addTab("Atualizar Produto", jPanel3);

        getContentPane().add(jTabbedPane1Guias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 560, 340));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/Agenda-PainelFundo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, 630, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagens/Tudo de Bom (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-650, 0, 1260, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1ProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1ProdutoMouseClicked
        jTabbedPane1Guias.setSelectedIndex(0);
        jTextField1NomeProduto.setText(jTable1Produto.getValueAt(jTable1Produto.getSelectedRow(), 0).toString());
        jTextField2CodigoProduto.setText(jTable1Produto.getValueAt(jTable1Produto.getSelectedRow(), 1).toString());
        jTextField3MarcaProduto.setText(jTable1Produto.getValueAt(jTable1Produto.getSelectedRow(), 2).toString());
        jTextField4QuantidadeProduto.setText(jTable1Produto.getValueAt(jTable1Produto.getSelectedRow(), 3).toString());
        jFormattedTextField1ValorProduto.setText(jTable1Produto.getValueAt(jTable1Produto.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_jTable1ProdutoMouseClicked

    private void jFormattedTextField1ValorProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ValorProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ValorProdutoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String message = "Deseja realmente apagar esse produto?";
        String title = "Confirmação";
        //Exibe caixa de dialogo (veja figura) solicitando confirmação ou não.
        //Se o usuário clicar em "Sim" retorna 0 pra variavel reply, se informado não retorna 1
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION){
            controller.deletar();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox2GenericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2GenericoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2GenericoActionPerformed

    private void jTextField4QuantidadeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4QuantidadeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4QuantidadeProdutoActionPerformed

    private void jFormattedTextField1ValorProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ValorProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ValorProduto1ActionPerformed

    private void jTextField4QuantidadeProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4QuantidadeProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4QuantidadeProduto1ActionPerformed

    private void jCheckBox2Generico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2Generico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2Generico1ActionPerformed

    private void jTextField3MarcaProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3MarcaProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3MarcaProduto1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            this.controller.atualizarProduto();        // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Estoque.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3buscarActionPerformed
    this.controller.buscar();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3buscarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            this.controller.cadastrar();        // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Estoque.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3buscar;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1Medicamento;
    private javax.swing.JCheckBox jCheckBox1Medicamento1;
    private javax.swing.JCheckBox jCheckBox2Generico;
    private javax.swing.JCheckBox jCheckBox2Generico1;
    private javax.swing.JFormattedTextField jFormattedTextField1ValorProduto;
    private javax.swing.JFormattedTextField jFormattedTextField1ValorProduto1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1Guias;
    private javax.swing.JTable jTable1Produto;
    private javax.swing.JTextField jTextField1NomeProduto;
    private javax.swing.JTextField jTextField1NomeProduto1;
    private javax.swing.JTextField jTextField2CodProduto;
    private javax.swing.JTextField jTextField2CodigoProduto;
    private javax.swing.JTextField jTextField2CodigoProduto1;
    private javax.swing.JTextField jTextField2NomProduto;
    private javax.swing.JTextField jTextField3MarcaProduto;
    private javax.swing.JTextField jTextField3MarcaProduto1;
    private javax.swing.JTextField jTextField4QuantidadeProduto;
    private javax.swing.JTextField jTextField4QuantidadeProduto1;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getjCheckBox1Medicamento() {
        return jCheckBox1Medicamento;
    }

    public void setjCheckBox1Medicamento(JCheckBox jCheckBox1Medicamento) {
        this.jCheckBox1Medicamento = jCheckBox1Medicamento;
    }

    public JCheckBox getjCheckBox2Generico() {
        return jCheckBox2Generico;
    }

    public void setjCheckBox2Generico(JCheckBox jCheckBox2Generico) {
        this.jCheckBox2Generico = jCheckBox2Generico;
    }

    public JFormattedTextField getjFormattedTextField1ValorProduto() {
        return jFormattedTextField1ValorProduto;
    }

    public void setjFormattedTextField1ValorProduto(JFormattedTextField jFormattedTextField1ValorProduto) {
        this.jFormattedTextField1ValorProduto = jFormattedTextField1ValorProduto;
    }

    public JTable getjTable1Produto() {
        return jTable1Produto;
    }

    public void setjTable1Produto(JTable jTable1Produto) {
        this.jTable1Produto = jTable1Produto;
    }

    public JTextField getjTextField1NomeProduto() {
        return jTextField1NomeProduto;
    }

    public void setjTextField1NomeProduto(JTextField jTextField1NomeProduto) {
        this.jTextField1NomeProduto = jTextField1NomeProduto;
    }

    public JTextField getjTextField2CodProduto() {
        return jTextField2CodProduto;
    }

    public void setjTextField2CodProduto(JTextField jTextField2CodProduto) {
        this.jTextField2CodProduto = jTextField2CodProduto;
    }

    public JTextField getjTextField2CodigoProduto() {
        return jTextField2CodigoProduto;
    }

    public void setjTextField2CodigoProduto(JTextField jTextField2CodigoProduto) {
        this.jTextField2CodigoProduto = jTextField2CodigoProduto;
    }

    public JTextField getjTextField2NomProduto() {
        return jTextField2NomProduto;
    }

    public void setjTextField2NomProduto(JTextField jTextField2NomProduto) {
        this.jTextField2NomProduto = jTextField2NomProduto;
    }

    public JTextField getjTextField3MarcaProduto() {
        return jTextField3MarcaProduto;
    }

    public void setjTextField3MarcaProduto(JTextField jTextField3MarcaProduto) {
        this.jTextField3MarcaProduto = jTextField3MarcaProduto;
    }

    public JTextField getjTextField4QuantidadeProduto() {
        return jTextField4QuantidadeProduto;
    }

    public void setjTextField4QuantidadeProduto(JTextField jTextField4QuantidadeProduto) {
        this.jTextField4QuantidadeProduto = jTextField4QuantidadeProduto;
    }

    public JTabbedPane getjTabbedPane1Guias() {
        return jTabbedPane1Guias;
    }

    public void setjTabbedPane1Guias(JTabbedPane jTabbedPane1Guias) {
        this.jTabbedPane1Guias = jTabbedPane1Guias;
    }

    public JCheckBox getjCheckBox1Medicamento1() {
        return jCheckBox1Medicamento1;
    }

    public void setjCheckBox1Medicamento1(JCheckBox jCheckBox1Medicamento1) {
        this.jCheckBox1Medicamento1 = jCheckBox1Medicamento1;
    }

    public JCheckBox getjCheckBox2Generico1() {
        return jCheckBox2Generico1;
    }

    public void setjCheckBox2Generico1(JCheckBox jCheckBox2Generico1) {
        this.jCheckBox2Generico1 = jCheckBox2Generico1;
    }

    public JFormattedTextField getjFormattedTextField1ValorProduto1() {
        return jFormattedTextField1ValorProduto1;
    }

    public void setjFormattedTextField1ValorProduto1(JFormattedTextField jFormattedTextField1ValorProduto1) {
        this.jFormattedTextField1ValorProduto1 = jFormattedTextField1ValorProduto1;
    }

    public JTextField getjTextField1NomeProduto1() {
        return jTextField1NomeProduto1;
    }

    public void setjTextField1NomeProduto1(JTextField jTextField1NomeProduto1) {
        this.jTextField1NomeProduto1 = jTextField1NomeProduto1;
    }

    public JTextField getjTextField2CodigoProduto1() {
        return jTextField2CodigoProduto1;
    }

    public void setjTextField2CodigoProduto1(JTextField jTextField2CodigoProduto1) {
        this.jTextField2CodigoProduto1 = jTextField2CodigoProduto1;
    }

    public JTextField getjTextField3MarcaProduto1() {
        return jTextField3MarcaProduto1;
    }

    public void setjTextField3MarcaProduto1(JTextField jTextField3MarcaProduto1) {
        this.jTextField3MarcaProduto1 = jTextField3MarcaProduto1;
    }

    public JTextField getjTextField4QuantidadeProduto1() {
        return jTextField4QuantidadeProduto1;
    }

    public void setjTextField4QuantidadeProduto1(JTextField jTextField4QuantidadeProduto1) {
        this.jTextField4QuantidadeProduto1 = jTextField4QuantidadeProduto1;
    }
    /** metodo que preenche a tabela de produtos assim que a tela de estoque é inicializada;
     * @uthor marcus lima
     * 
     */
    
private void listarValores() {
            try {
                ProdutoDAO objProduto = new ProdutoDAO();

                DefaultTableModel model;
                model = (DefaultTableModel) this.getjTable1Produto().getModel();
                model.setNumRows(0);

                ArrayList<Produto> listaProdutos = objProduto.listarProduto();

                listaProdutos.stream().forEach((listaProduto) -> {
                     model.addRow(new Object[]{listaProduto.getId(), listaProduto.getNomeProduto(),listaProduto.getMarcaProduto(),listaProduto.getQuantidadeProduto() ,listaProduto.getQuantidadeAtualProduto(),listaProduto.getQuantidadeVendidaProduto() , listaProduto.getValorProduto(), listaProduto.getValorDescontoProduto(), listaProduto.getValorAtualProduto()});
                });

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Estoque" + erro.getMessage());
            }
            
    }



}
