/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EstoqueController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author marcu
 */
public class Estoque extends javax.swing.JFrame {

    /**
     * Creates new form Estoque
     */
    
    EstoqueController controller;
    
    public Estoque() {
        initComponents();
        this.controller = new EstoqueController(this);
        this.controller.preencharTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTabbedPane1Guias = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField4QuantidadeProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3MarcaProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2CodigoProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1NomeProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox2Generico = new javax.swing.JCheckBox();
        jCheckBox1Medicamento = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtValor = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2NomProduto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2CodProduto = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Produto = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1Guias.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField4QuantidadeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4QuantidadeProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4QuantidadeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 160, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Quantidadedo produto:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel1.add(jTextField3MarcaProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Marca do produto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel1.add(jTextField2CodigoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nome do produto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel1.add(jTextField1NomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 300, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Código do produto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jCheckBox2Generico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox2Generico.setText("Genérico");
        jCheckBox2Generico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2GenericoActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2Generico, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 130, 30));

        jCheckBox1Medicamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1Medicamento.setText("Medicamento");
        jPanel1.add(jCheckBox1Medicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Valor do produto:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, 20));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Cadastrar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 140, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Editar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 140, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Apagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 140, 50));
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 120, 30));

        jTabbedPane1Guias.addTab("Cadastro de Produto", jPanel1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nome do produto:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Código do produto:");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Buscar");

        jTable1Produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Marca", "Quantidade", "Valor"
            }
        ));
        jTable1Produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1ProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1Produto);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField2NomProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2CodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2NomProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2CodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        jTabbedPane1Guias.addTab("Consulta de produtos", jPanel2);

        getContentPane().add(jTabbedPane1Guias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 560, 340));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Agenda-PainelFundo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, 630, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Tudo de Bom (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-650, 0, 1260, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1ProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1ProdutoMouseClicked
        jTabbedPane1Guias.setSelectedIndex(0);
        jTextField1NomeProduto.setText(jTable1Produto.getValueAt(jTable1Produto.getSelectedRow(), 0).toString());
        jTextField2CodigoProduto.setText(jTable1Produto.getValueAt(jTable1Produto.getSelectedRow(), 1).toString());
        jTextField3MarcaProduto.setText(jTable1Produto.getValueAt(jTable1Produto.getSelectedRow(), 2).toString());
        jTextField4QuantidadeProduto.setText(jTable1Produto.getValueAt(jTable1Produto.getSelectedRow(), 3).toString());
        txtValor.setText(jTable1Produto.getValueAt(jTable1Produto.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_jTable1ProdutoMouseClicked

    private void jCheckBox2GenericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2GenericoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2GenericoActionPerformed

    private void jTextField4QuantidadeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4QuantidadeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4QuantidadeProdutoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String message = "Deseja realmente apagar esse produto?";
      String title = "Confirmação";
      //Exibe caixa de dialogo (veja figura) solicitando confirmação ou não. 
      //Se o usuário clicar em "Sim" retorna 0 pra variavel reply, se informado não retorna 1
      int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
      if (reply == JOptionPane.YES_OPTION){
         try {
             controller.deletar();
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(Estoque.class.getName()).log(Level.SEVERE, null, ex);
         }
      }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        try {
            controller.cadastrar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Estoque.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1Medicamento;
    private javax.swing.JCheckBox jCheckBox2Generico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1Guias;
    private javax.swing.JTable jTable1Produto;
    private javax.swing.JTextField jTextField1NomeProduto;
    private javax.swing.JTextField jTextField2CodProduto;
    private javax.swing.JTextField jTextField2CodigoProduto;
    private javax.swing.JTextField jTextField2NomProduto;
    private javax.swing.JTextField jTextField3MarcaProduto;
    private javax.swing.JTextField jTextField4QuantidadeProduto;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getjCheckBox1Medicamento() {
        return jCheckBox1Medicamento;
    }

    public void setjCheckBox1Medicamento(JCheckBox jCheckBox1Medicamento) {
        this.jCheckBox1Medicamento = jCheckBox1Medicamento;
    }

    public JCheckBox getjCheckBox2Generico() {
        return jCheckBox2Generico;
    }

    public void setjCheckBox2Generico(JCheckBox jCheckBox2Generico) {
        this.jCheckBox2Generico = jCheckBox2Generico;
    }

    public JTextField getTxtValor() {
        return txtValor;
    }

    public void setTxtValor(JTextField txtValor) {
        this.txtValor = txtValor;
    }

    public JTable getjTable1Produto() {
        return jTable1Produto;
    }

    public void setjTable1Produto(JTable jTable1Produto) {
        this.jTable1Produto = jTable1Produto;
    }

    public JTextField getjTextField1NomeProduto() {
        return jTextField1NomeProduto;
    }

    public void setjTextField1NomeProduto(JTextField jTextField1NomeProduto) {
        this.jTextField1NomeProduto = jTextField1NomeProduto;
    }

    public JTextField getjTextField2CodProduto() {
        return jTextField2CodProduto;
    }

    public void setjTextField2CodProduto(JTextField jTextField2CodProduto) {
        this.jTextField2CodProduto = jTextField2CodProduto;
    }

    public JTextField getjTextField2CodigoProduto() {
        return jTextField2CodigoProduto;
    }

    public void setjTextField2CodigoProduto(JTextField jTextField2CodigoProduto) {
        this.jTextField2CodigoProduto = jTextField2CodigoProduto;
    }

    public JTextField getjTextField2NomProduto() {
        return jTextField2NomProduto;
    }

    public void setjTextField2NomProduto(JTextField jTextField2NomProduto) {
        this.jTextField2NomProduto = jTextField2NomProduto;
    }

    public JTextField getjTextField3MarcaProduto() {
        return jTextField3MarcaProduto;
    }

    public void setjTextField3MarcaProduto(JTextField jTextField3MarcaProduto) {
        this.jTextField3MarcaProduto = jTextField3MarcaProduto;
    }

    public JTextField getjTextField4QuantidadeProduto() {
        return jTextField4QuantidadeProduto;
    }

    public void setjTextField4QuantidadeProduto(JTextField jTextField4QuantidadeProduto) {
        this.jTextField4QuantidadeProduto = jTextField4QuantidadeProduto;
    }

    public JTabbedPane getjTabbedPane1Guias() {
        return jTabbedPane1Guias;
    }

    public void setjTabbedPane1Guias(JTabbedPane jTabbedPane1Guias) {
        this.jTabbedPane1Guias = jTabbedPane1Guias;
    }

}
